export type TopicOption = {
  /** Stored value (also what we put in User.interests). */
  value: string;
  /** Human-friendly label. */
  label: string;
  /** Group used by pickers/UI. */
  group: string;
  /** Alternate spellings/phrases that should map to `value`. */
  aliases?: string[];
};

/**
 * Canonical topic allowlist.
 *
 * This is used for:
 * - Explore “Topics” (so we never show garbage tokens like “ipsum”)
 * - Interests picker suggestions (mapping inferred text -> stable values)
 *
 * NOTE: Keep this list in sync with the www app’s interest/topic options.
 */
export const TOPIC_OPTIONS: TopicOption[] = [
  // Religion (14)
  { value: 'faith', label: 'Faith', group: 'Religion', aliases: ['religion', 'spiritual', 'spirituality', 'god', 'church'] },
  { value: 'christianity', label: 'Christianity', group: 'Religion', aliases: ['christian', 'jesus', 'christ'] },
  { value: 'bible', label: 'Bible', group: 'Religion', aliases: ['bible study', 'bible_study', 'scripture'] },
  { value: 'prayer', label: 'Prayer', group: 'Religion', aliases: ['pray', 'praying'] },
  { value: 'church', label: 'Church', group: 'Religion', aliases: ['worship', 'sermon', 'congregation', 'fellowship'] },
  { value: 'theology', label: 'Theology', group: 'Religion', aliases: ['doctrine'] },
  { value: 'apologetics', label: 'Apologetics', group: 'Religion', aliases: ['defend the faith'] },
  { value: 'discipleship', label: 'Discipleship', group: 'Religion', aliases: ['sanctification'] },
  { value: 'catholicism', label: 'Catholicism', group: 'Religion', aliases: ['catholic', 'mass', 'rosary', 'pope'] },
  { value: 'protestantism', label: 'Protestantism', group: 'Religion', aliases: ['protestant', 'baptist', 'methodist', 'lutheran', 'evangelical'] },
  { value: 'orthodox_christianity', label: 'Orthodox Christianity', group: 'Religion', aliases: ['orthodox', 'eastern orthodox', 'orthodoxy'] },
  { value: 'islam', label: 'Islam', group: 'Religion', aliases: ['muslim', 'quran', 'koran'] },
  { value: 'judaism', label: 'Judaism', group: 'Religion', aliases: ['jewish', 'torah'] },
  { value: 'buddhism', label: 'Buddhism', group: 'Religion', aliases: ['buddhist', 'dharma'] },

  // Politics (14)
  { value: 'current_events', label: 'Current events', group: 'Politics', aliases: ['news', 'breaking news'] },
  { value: 'politics', label: 'Politics', group: 'Politics', aliases: ['political', 'congress', 'senate'] },
  { value: 'elections', label: 'Elections', group: 'Politics', aliases: ['voting', 'ballot', 'primary'] },
  { value: 'policy', label: 'Policy', group: 'Politics', aliases: ['public policy'] },
  { value: 'law', label: 'Law', group: 'Politics', aliases: ['legal', 'court', 'supreme court'] },
  { value: 'civics', label: 'Civics', group: 'Politics', aliases: ['government', 'constitution'] },
  { value: 'economics', label: 'Economics', group: 'Politics', aliases: ['economy', 'inflation', 'gdp', 'recession'] },
  { value: 'geopolitics', label: 'Geopolitics', group: 'Politics', aliases: ['international relations', 'foreign policy', 'war'] },
  { value: 'media', label: 'Media', group: 'Politics', aliases: ['journalism', 'press'] },
  { value: 'immigration', label: 'Immigration', group: 'Politics', aliases: ['border', 'asylum'] },
  { value: 'education_policy', label: 'Education policy', group: 'Politics', aliases: ['schools', 'school choice'] },
  { value: 'healthcare_policy', label: 'Healthcare policy', group: 'Politics', aliases: ['healthcare', 'medicare', 'medicaid'] },
  { value: 'taxation', label: 'Taxation', group: 'Politics', aliases: ['taxes', 'irs'] },
  { value: 'political_philosophy', label: 'Political philosophy', group: 'Politics', aliases: ['liberalism', 'conservatism', 'libertarian', 'socialism'] },

  // Business (14)
  { value: 'entrepreneurship', label: 'Entrepreneurship', group: 'Business', aliases: ['entrepreneur', 'founder'] },
  { value: 'startups', label: 'Startups', group: 'Business', aliases: ['startup', 'saas', 'bootstrapping'] },
  { value: 'investing', label: 'Investing', group: 'Business', aliases: ['stocks', 'etf', 'index funds', '401k', 'roth', 'dividends'] },
  { value: 'personal_finance', label: 'Personal finance', group: 'Business', aliases: ['budget', 'saving', 'debt', 'credit'] },
  { value: 'real_estate', label: 'Real estate', group: 'Business', aliases: ['realestate', 'mortgage', 'rental property', 'airbnb'] },
  { value: 'career_growth', label: 'Career growth', group: 'Business', aliases: ['career', 'jobs', 'resume', 'interview', 'promotion'] },
  { value: 'leadership', label: 'Leadership', group: 'Business', aliases: ['leading', 'lead'] },
  { value: 'management', label: 'Management', group: 'Business', aliases: ['manager', 'managing'] },
  { value: 'marketing', label: 'Marketing', group: 'Business', aliases: ['brand', 'advertising'] },
  { value: 'sales', label: 'Sales', group: 'Business', aliases: ['selling', 'closing'] },
  { value: 'product_management', label: 'Product management', group: 'Business', aliases: ['pm', 'product manager'] },
  { value: 'small_business', label: 'Small business', group: 'Business', aliases: ['local business'] },
  { value: 'crypto', label: 'Crypto', group: 'Business', aliases: ['cryptocurrency', 'bitcoin', 'btc', 'ethereum', 'eth'] },
  { value: 'productivity', label: 'Productivity', group: 'Business', aliases: ['time management', 'focus'] },

  // Technology (14)
  {
    value: 'ai',
    label: 'AI',
    group: 'Technology',
    aliases: [
      'artificial intelligence',
      'machine learning',
      'deep learning',
      'ml',
      'llm',
      'llms',
      'large language model',
      'large language models',
      'generative ai',
      'gen ai',
      'chatbot',
      'openai',
      'chatgpt',
      'gpt',
      'anthropic',
      'claude',
      'google ai',
      'gemini',
      'deepmind',
      'meta ai',
      'llama',
      'mistral',
      'cohere',
      'hugging face',
      'xai',
      'x ai',
      'x.ai',
      'grok',
      'prompt',
      'prompting',
      'prompt engineering',
      'fine tuning',
      'finetuning',
      'rag',
      'retrieval augmented generation',
      'embeddings',
      'vector database',
      'vector db',
      'token',
      'tokens',
      'inference',
      'stable diffusion',
      'midjourney',
      'dalle',
      'dall e',
      'whisper',
    ],
  },
  { value: 'programming', label: 'Programming', group: 'Technology', aliases: ['coding', 'developer', 'software engineer', 'engineering', 'github', 'open source'] },
  { value: 'web_development', label: 'Web development', group: 'Technology', aliases: ['web dev', 'frontend', 'backend', 'react', 'vue', 'nuxt', 'node'] },
  { value: 'mobile_development', label: 'Mobile development', group: 'Technology', aliases: ['ios', 'android', 'swift', 'kotlin'] },
  { value: 'cybersecurity', label: 'Cybersecurity', group: 'Technology', aliases: ['infosec', 'security', 'pentest', 'vulnerability', 'breach', 'malware', 'ransomware', 'phishing', 'cve', 'ctf'] },
  { value: 'cloud', label: 'Cloud', group: 'Technology', aliases: ['aws', 'gcp', 'azure'] },
  { value: 'devops', label: 'DevOps', group: 'Technology', aliases: ['ci', 'cd', 'kubernetes', 'docker', 'terraform'] },
  { value: 'data_science', label: 'Data science', group: 'Technology', aliases: ['data', 'analytics', 'statistics', 'pandas'] },
  { value: 'hardware', label: 'Hardware', group: 'Technology', aliases: ['pc building', 'chips', 'cpu', 'gpu'] },
  { value: 'gadgets', label: 'Gadgets', group: 'Technology', aliases: ['gadgets', 'gear'] },
  { value: 'gaming', label: 'Gaming', group: 'Technology', aliases: ['games', 'video games', 'pc gaming', 'steam', 'xbox', 'playstation', 'ps5', 'nintendo', 'switch'] },
  { value: 'privacy', label: 'Privacy', group: 'Technology', aliases: ['privacy', 'surveillance'] },
  { value: 'open_source', label: 'Open source', group: 'Technology', aliases: ['oss', 'open-source'] },
  { value: 'tech_news', label: 'Tech news', group: 'Technology', aliases: ['technology', 'tech'] },

  // Health (14)
  {
    value: 'strength_training',
    label: 'Strength training',
    group: 'Health',
    aliases: [
      // Legacy fitness topics
      'weightlifting',
      'powerlifting',
      'bodybuilding',
      'crossfit',
      'calisthenics',
      'kettlebells',
      'strongman',
      // Common terms
      'gym',
      'strength',
      'lifting',
      'hypertrophy',
      'squat',
      'bench',
      'deadlift',
    ],
  },
  {
    value: 'endurance_training',
    label: 'Endurance training',
    group: 'Health',
    aliases: [
      'running',
      'trail_running',
      'trail running',
      'cycling',
      'swimming',
      'triathlon',
      'rowing',
      'cardio',
      'aerobic',
      'marathon',
      'ironman',
    ],
  },
  {
    value: 'sports',
    label: 'Sports',
    group: 'Health',
    aliases: ['sports', 'basketball', 'soccer', 'baseball', 'football', 'hockey', 'tennis', 'pickleball', 'golf', 'athlete'],
  },
  {
    value: 'combat_sports',
    label: 'Combat sports',
    group: 'Health',
    aliases: ['combat sports', 'martial_arts', 'martial arts', 'boxing', 'kickboxing', 'muay_thai', 'muay thai', 'mma', 'wrestling', 'judo', 'jiu_jitsu', 'bjj'],
  },
  {
    value: 'outdoors',
    label: 'Outdoors',
    group: 'Health',
    aliases: ['outdoors', 'outdoor', 'nature', 'hiking', 'camping', 'backpacking', 'fishing', 'hunting', 'climbing', 'skiing', 'snowboarding', 'kayaking'],
  },
  {
    value: 'nutrition',
    label: 'Nutrition',
    group: 'Health',
    aliases: [
      // Legacy food/drink topics
      'cooking',
      'bbq',
      'coffee',
      'whiskey',
      'craft_beer',
      // Diet terms
      'diet',
      'macros',
      'protein',
      'calories',
      'cutting',
      'bulking',
      'keto',
      'carnivore',
      'intermittent fasting',
    ],
  },
  { value: 'sleep', label: 'Sleep', group: 'Health', aliases: ['sleep', 'insomnia', 'sleep apnea'] },
  { value: 'mental_health', label: 'Mental health', group: 'Health', aliases: ['therapy', 'anxiety', 'depression', 'counseling'] },
  { value: 'meditation', label: 'Meditation', group: 'Health', aliases: ['mindfulness', 'breathwork', 'breathing'] },
  { value: 'mobility', label: 'Mobility', group: 'Health', aliases: ['mobility', 'stretching', 'range of motion', 'rom', 'foam rolling', 'prehab', 'yoga'] },
  { value: 'recovery', label: 'Recovery', group: 'Health', aliases: ['recovery', 'rest', 'injury', 'rehab'] },
  { value: 'mens_health', label: "Men's health", group: 'Health', aliases: ['mens health', "men's health", 'testosterone', 'trt'] },
  { value: 'weight_loss', label: 'Weight loss', group: 'Health', aliases: ['weight loss', 'fat loss', 'cut'] },
  { value: 'longevity', label: 'Longevity', group: 'Health', aliases: ['longevity', 'biohacking', 'healthspan'] },

  // Relationships (14)
  { value: 'dating', label: 'Dating', group: 'Relationships', aliases: ['dating', 'single', 'apps'] },
  { value: 'marriage', label: 'Marriage', group: 'Relationships', aliases: ['marriage', 'husband', 'wife'] },
  { value: 'fatherhood', label: 'Fatherhood', group: 'Relationships', aliases: ['dad', 'dads', 'parenting'] },
  { value: 'family', label: 'Family', group: 'Relationships', aliases: ['family', 'kids', 'parenting'] },
  { value: 'friendship', label: 'Friendship', group: 'Relationships', aliases: ['friends', 'friendship'] },
  { value: 'brotherhood', label: 'Brotherhood', group: 'Relationships', aliases: ['mens groups', "men's groups", 'mens_groups', "men's group", 'brotherhood'] },
  { value: 'mentorship', label: 'Mentorship', group: 'Relationships', aliases: ['mentoring', 'mentor', 'coaching'] },
  { value: 'community', label: 'Community', group: 'Relationships', aliases: ['community', 'volunteering', 'service', 'volunteer', 'charity', 'nonprofit'] },
  { value: 'communication', label: 'Communication', group: 'Relationships', aliases: ['communication', 'listening'] },
  { value: 'conflict_resolution', label: 'Conflict resolution', group: 'Relationships', aliases: ['conflict', 'arguments', 'repair'] },
  { value: 'boundaries', label: 'Boundaries', group: 'Relationships', aliases: ['boundaries'] },
  { value: 'divorce', label: 'Divorce', group: 'Relationships', aliases: ['divorce', 'separation', 'custody'] },
  { value: 'intimacy', label: 'Intimacy', group: 'Relationships', aliases: ['intimacy', 'sex', 'sexuality'] },
  { value: 'forgiveness', label: 'Forgiveness', group: 'Relationships', aliases: ['forgiveness', 'resentment'] },

  // Philosophy (14)
  { value: 'philosophy', label: 'Philosophy', group: 'Philosophy', aliases: ['philosophy', 'philosophical'] },
  { value: 'stoicism', label: 'Stoicism', group: 'Philosophy', aliases: ['stoic', 'stoicism'] },
  { value: 'ethics', label: 'Ethics', group: 'Philosophy', aliases: ['ethics', 'morality', 'virtue'] },
  { value: 'meaning_and_purpose', label: 'Meaning & purpose', group: 'Philosophy', aliases: ['meaning', 'purpose', 'calling'] },
  { value: 'self_discipline', label: 'Self-discipline', group: 'Philosophy', aliases: ['discipline', 'willpower'] },
  { value: 'habits', label: 'Habits', group: 'Philosophy', aliases: ['habits', 'routine'] },
  { value: 'psychology', label: 'Psychology', group: 'Philosophy', aliases: ['psychology'] },
  { value: 'books', label: 'Books', group: 'Philosophy', aliases: ['reading', 'kindle', 'goodreads', 'audiobook', 'audiobooks'] },
  { value: 'podcasts', label: 'Podcasts', group: 'Philosophy', aliases: ['podcast'] },
  { value: 'history', label: 'History', group: 'Philosophy', aliases: ['history'] },
  { value: 'learning', label: 'Learning', group: 'Philosophy', aliases: ['learning', 'education', 'study', 'language_learning', 'language learning', 'duolingo', 'anki', 'flashcards'] },
  { value: 'art_and_culture', label: 'Art & culture', group: 'Philosophy', aliases: ['music', 'guitar', 'photography', 'movies', 'film', 'art', 'arts'] },
  { value: 'travel_and_life', label: 'Travel & life', group: 'Philosophy', aliases: ['travel', 'road_trips', 'road trips', 'roadtrip', 'vanlife'] },
  { value: 'spirituality', label: 'Spirituality', group: 'Philosophy', aliases: ['spirituality'] },
];

