// Shared discovery for the panel, MARV, MCP, and CLI. Paths are product links,
// never API targets supplied by the model. Long-tail actions remain in their editor.
export const adminCapabilities = [
  { id: 'attention', section: 'Overview', title: 'Attention inbox', path: '/admin/attention', icon: 'tabler:inbox', summary: 'Review pending work and conversations needing a human reply', tools: ['admin_workspace'], ios: 'web' },
  { id: 'activation', section: 'Overview', title: 'Member activation', path: '/admin/activation', icon: 'tabler:chart-funnel', summary: 'Explore signup, verification, first contribution, and return milestones', tools: ['member_activation'], ios: 'web' },
  { id: 'assistant', section: 'Overview', title: 'Ask MARV', path: '/admin/assistant', icon: 'tabler:sparkles', summary: 'Check the business and prepare admin actions', tools: ['founder_briefing', 'metric_definitions'], ios: 'web' },
  { id: 'delegation', section: 'Overview', title: 'Delegated work', path: '/admin/delegation', icon: 'tabler:calendar-check', summary: 'Schedule sourced news, prepare community follow-up, and review actions as yourself or an operated page', tools: ['delegation_workspace', 'delegation_job', 'create_delegated_job', 'edit_delegated_job', 'control_delegated_job', 'decide_delegated_action'], ios: 'native' },
  { id: 'users', section: 'People', title: 'Users', path: '/admin/users', icon: 'tabler:users', summary: 'Profiles, bans, grants, coins, pages, organizations, and operators', tools: ['search_members', 'member_profile', 'member_diagnostics', 'member_grants', 'member_referrals'], ios: 'web' },
  { id: 'impersonate', section: 'People', title: 'Log in as user', path: '/admin/impersonate', icon: 'tabler:eye', summary: 'Inspect a member experience; direct admin control only', tools: [], ios: 'native' },
  { id: 'verification', section: 'People', title: 'Verification', path: '/admin/verification', icon: 'tabler:rosette-discount-check', summary: 'Review requests and approve or reject members', tools: ['admin_workspace'], ios: 'web' },
  { id: 'media-review', section: 'Content', title: 'Media review', path: '/admin/media-review', icon: 'tabler:photo', summary: 'Inspect references and delete uploaded images or videos', tools: [], ios: 'web' },
  { id: 'reports', section: 'Content', title: 'Reports', path: '/admin/reports', icon: 'tabler:flag', summary: 'Review reported posts and users', tools: ['reports'], ios: 'native' },
  { id: 'feedback', section: 'Content', title: 'Feedback', path: '/admin/feedback', icon: 'tabler:inbox', summary: 'Read and triage member feedback', tools: ['feedback'], ios: 'native' },
  { id: 'announcements', section: 'Content', title: 'Announcements', path: '/admin/announcements', icon: 'tabler:speakerphone', summary: 'Draft, publish, archive, and reset lodge notices or ads', tools: ['admin_workspace'], ios: 'native' },
  { id: 'newsletters', section: 'Content', title: 'Newsletter', path: '/admin/newsletters', icon: 'tabler:mail', summary: 'Draft, preview, target, schedule, and send the lodge letter', tools: ['newsletters'], ios: 'web' },
  { id: 'search', section: 'Platform', title: 'Search', path: '/admin/search', icon: 'tabler:search', summary: 'Review recent typed member searches', tools: ['admin_workspace'], ios: 'native' },
  { id: 'analytics', section: 'Platform', title: 'Analytics', path: '/admin/analytics', icon: 'tabler:chart-bar', summary: 'Growth, retention, activity, membership, AI, coins, and referrals', tools: ['analytics', 'referral_analytics'], ios: 'native' },
  { id: 'push', section: 'Platform', title: 'Push notifications', path: '/admin/push', icon: 'tabler:bell-ringing', summary: 'Send test iOS or web pushes to your own account', tools: [], ios: 'native' },
  { id: 'jobs', section: 'Platform', title: 'Jobs', path: '/admin/jobs', icon: 'tabler:terminal-2', summary: 'Queue health, cleanup, backfills, and daily content', tools: ['queue_health', 'operations_health', 'admin_workspace'], ios: 'web' },
  { id: 'site-settings', section: 'Platform', title: 'Site settings', path: '/admin/site-settings', icon: 'tabler:settings', summary: 'Post limits, automatic verification, and email samples', tools: ['admin_workspace'], ios: 'web' },
  { id: 'marv', section: 'AI & Monetization', title: 'MARV settings', path: '/admin/marv', icon: 'tabler:robot', summary: 'Models, credits, member controls, context cards, usage, and cost', tools: ['admin_workspace'], ios: 'web' },
  { id: 'intros', section: 'AI & Monetization', title: 'Intros', path: '/admin/intros', icon: 'tabler:user-plus', summary: 'Generate and review weekly introduction suggestions', tools: ['admin_workspace'], ios: 'web' },
  { id: 'affiliates', section: 'AI & Monetization', title: 'Referral Pilot', path: '/admin/affiliates', icon: 'tabler:coins', summary: 'Pilot membership, accrued earnings, and payout settlement', tools: ['admin_workspace', 'referral_analytics'], ios: 'web' },
  { id: 'crews', section: 'More tools', title: 'Crews', path: null, icon: 'tabler:users-group', summary: 'API supports crew inspection, ownership transfer, and disbanding; no admin editor yet', tools: ['admin_workspace'], ios: 'assistant' },
  { id: 'contextual-admin', section: 'More tools', title: 'Post and group controls', path: null, icon: 'tabler:shield', summary: 'Post editing and ranking details, group settings, pins and moderators, and crew settings live on the relevant post, group, or crew screens', tools: [], ios: 'contextual' },
  { id: 'diagnostics', section: 'More tools', title: 'Deployment diagnostics', path: null, icon: 'tabler:heartbeat', summary: 'Admin-only health configuration is available through the API; deployment changes require infrastructure access', tools: [], ios: 'unavailable' },
  { id: 'local-artifacts', section: 'More tools', title: 'Local drafts and decisions', path: null, icon: 'tabler:notes', summary: 'CLI and desktop MCP files stay on your computer; hosted MARV cannot read them', tools: ['record_decision', 'save_draft', 'list_decisions', 'list_drafts'], ios: 'unavailable' },
];

export const workspaceReads = {
  attention: { path: 'admin/operations/attention' },
  verification: { path: 'admin/verification', paginated: true },
  announcements: { path: 'admin/announcements' },
  searches: { path: 'admin/searches', paginated: true },
  site_settings: { path: 'admin/site-config' },
  marv_config: { path: 'admin/marvin/config' },
  marv_users: { path: 'admin/marvin/users', paginated: true },
  marv_usage: { path: 'admin/marvin/usage', paginated: true },
  marv_cost: { path: 'admin/marvin/cost' },
  intros: { path: 'admin/intros/brief' },
  affiliates: { path: 'admin/affiliates' },
  daily_content: { path: 'admin/daily-content/today' },
  crews: { path: 'admin/crews' },
};
