import "reflect-metadata";
import { writeFileSync, readFileSync } from "node:fs";
import { adminActions } from "../src/modules/admin/admin-assistant-actions";
import { sharedTools } from "../src/modules/mcp/mcp-tools";
import { workflowOperations } from "../src/modules/admin/delegation/delegation.schemas";
import { createRequire } from "node:module";
import { resolve } from "node:path";
const { createTools } = createRequire(__filename)(
  resolve("tools/mcp/src/tools.mjs"),
);
const catalog = (localArtifacts: boolean, remoteWrites: boolean) =>
  createTools({ api: {}, store: {}, localArtifacts, remoteWrites })
    .map(
      (t: { name: string; remoteWrite: boolean }) =>
        `${t.name}${t.remoteWrite ? " (write)" : ""}`,
    )
    .sort();
const output = `# Generated MARV and MCP capabilities\n\nGenerated by \`npm run emit:mcp-capabilities\`. Do not edit this inventory by hand.\n\n${[
  ["Desktop / CLI", catalog(true, true)],
  ["Hosted read scope", catalog(false, false)],
  ["Hosted write scope", catalog(false, true)],
  [
    "Ask MARV reads",
    sharedTools
      .createTools({ api: {} as any, localArtifacts: false })
      .map((t) => t.name)
      .sort(),
  ],
  ["Ask MARV reviewed proposals", adminActions.map((a) => a.name).sort()],
]
  .map(
    ([title, entries]) =>
      `## ${title}\n\n${(entries as string[]).map((e) => `- ${e}`).join("\n")}\n`,
  )
  .join("\n")}\n## Delegated workflows\n\n${Object.entries(workflowOperations)
  .map(([name, ops]) => `- **${name}**: ${ops.join(", ")}`)
  .join(
    "\n",
  )}\n\nHosted writes require write scope and explicit authorization. Ask MARV proposals require an in-product confirmation. All delegated actions require review except explicitly authorized sourced-news publication. Scheduled jobs retain their own authorization until paused/cancelled; removing a connector is not cancellation.\n`;
const path = "docs/mcp-capabilities.md";
if (process.argv.includes("--check")) {
  if (readFileSync(path, "utf8") !== output)
    throw new Error(
      "MCP capabilities drift; run npm run emit:mcp-capabilities.",
    );
} else writeFileSync(path, output);
