import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { contractFixtures } from '../src/common/dto/contract-fixtures';

const root = resolve(__dirname, '..');
const check = process.argv.includes('--check');
const json = JSON.stringify(contractFixtures, null, 2) + '\n';
const outputs = new Map([
  [resolve(root, 'contracts/fixtures/release.json'), json],
]);
const www = resolve(root, '../menofhunger-www');
const ios = resolve(root, '../menofhunger-ios');
if (existsSync(www)) outputs.set(resolve(www, 'tests/fixtures/api-contracts.gen.ts'),
  '// Generated by API npm run sync:contract-fixtures. Do not edit.\n'
  + "import type { BillingMe, MarvinMeDto } from '../../types/api'\n"
  + "import type { AccountDeletionRequestDto } from '../../types/api-contracts.gen'\n"
  + `export const contractFixtures = ${json.trim()} satisfies { billing: Record<string, BillingMe>; marvin: MarvinMeDto; deletion: AccountDeletionRequestDto }\n`);
if (existsSync(ios)) outputs.set(resolve(ios, 'MenOfHungerTests/Fixtures/release-contracts.json'), json);
for (const [path, content] of outputs) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
      console.error(`Stale contract fixture: ${path}; run npm run sync:contract-fixtures`);
      process.exitCode = 1;
    }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
}
console.log(`Contract fixtures ${check ? 'checked' : 'synced'} (${outputs.size} files).`);
