import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { contractFixtures } from "../src/common/dto/contract-fixtures";
import { apiResponseFixturesByDomain } from "../src/common/dto/api-response-fixtures";

export function fixtureOutputs(
  root: string,
  iosRoot?: string,
  androidRoot?: string,
): Map<string, string> {
  const json = JSON.stringify(contractFixtures, null, 2) + "\n";
  const outputs = new Map([
    [resolve(root, "contracts/fixtures/release.json"), json],
  ]);
  const www = resolve(root, "../menofhunger-www");
  const ios = iosRoot ? resolve(iosRoot) : resolve(root, "../menofhunger-ios");
  if (existsSync(www))
    outputs.set(
      resolve(www, "tests/fixtures/api-contracts.gen.ts"),
      "// Generated by API npm run sync:contract-fixtures. Do not edit.\n" +
        "import type { BillingMe, MarvinMeDto } from '../../types/api'\n" +
        "import type { AccountDeletionRequestDto } from '../../types/api-contracts.gen'\n" +
        `export const contractFixtures = ${json.trim()} satisfies { billing: Record<string, BillingMe>; marvin: MarvinMeDto; deletion: AccountDeletionRequestDto }\n`,
    );
  if (existsSync(ios))
    outputs.set(
      resolve(ios, "MenOfHungerTests/Fixtures/release-contracts.json"),
      json,
    );
  for (const [domain, fixtures] of Object.entries(
    apiResponseFixturesByDomain,
  )) {
    const domainJson = JSON.stringify(fixtures, null, 2) + "\n";
    outputs.set(resolve(root, `contracts/fixtures/${domain}.json`), domainJson);
    if (androidRoot)
      outputs.set(
        resolve(androidRoot, `app/src/test/resources/contracts/${domain}.json`),
        domainJson,
      );
  }
  return outputs;
}

export function syncFixtures(
  outputs: Map<string, string>,
  check: boolean,
): string[] {
  const stale: string[] = [];
  for (const [path, content] of outputs) {
    if (check) {
      if (!existsSync(path) || readFileSync(path, "utf8") !== content)
        stale.push(path);
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, content);
    }
  }
  return stale;
}

export function fixtureOptions(argv: string[]): {
  check: boolean;
  iosRoot?: string;
  androidRoot?: string;
} {
  const options: { check: boolean; iosRoot?: string; androidRoot?: string } = {
    check: false,
  };
  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index];
    if (arg === "--check") options.check = true;
    else if (arg === "--ios-root" || arg === "--android-root") {
      const value = argv[++index];
      if (!value || value.startsWith("--"))
        throw new Error(`${arg} requires a checkout path`);
      if (!existsSync(resolve(value)))
        throw new Error(`Missing checkout: ${value}`);
      if (arg === "--ios-root") options.iosRoot = value;
      else options.androidRoot = value;
    } else throw new Error(`Unknown option: ${arg}`);
  }
  return options;
}

if (require.main === module) {
  const root = resolve(__dirname, "..");
  const options = fixtureOptions(process.argv.slice(2));
  const outputs = fixtureOutputs(root, options.iosRoot, options.androidRoot);
  const stale = syncFixtures(outputs, options.check);
  for (const path of stale)
    console.error(
      `Stale contract fixture: ${path}; run npm run sync:contract-fixtures with the same checkout overrides`,
    );
  if (stale.length) process.exitCode = 1;
  console.log(
    `Contract fixtures ${options.check ? "checked" : "synced"} (${outputs.size} files).`,
  );
}
